[mimicSettings]
mimicDifficulty = "MEDIUM"
spawnNaturalMimics = true
naturalMimicSpawnRate = 0.85
allowPetMimics = true
doPetMimicLimit = false
petMimicLimit = 2
abandonedMimicTimer = 5
allowPetMimicLocking = true
[worldGen]
potSpawnChance = 0.3
chestSpawnChance = 0.5
surfaceChestSpawnChance = 0.5
secretMimicChance = 0.25
[chestSettings]
allowChestLocking = true
enableLockedChestOwners = true
