name = "All Bits of Fabric"
author = "NoxNoire,AOF5Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1816fc99fd047766aa690e752f51d1979f5f3ed2c25ac281aad9dd87fc7fcc51"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
